version: '2'
services:
    db:
        image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: item8frog
          MYSQL_DATABASE: test_db
          MYSQL_USER: root
          MYSQL_PASSWORD: item8frog
        ports:
          - "9906:3306"
    php:
        build:
            "."
        image: phpdocker
        container_name: php
        restart:
            always
        ports:            
            - 9000:80            
        volumes:
            - "../:/var/www/html/"            
        depends_on:
            - db